### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sakura818** [sakura818/write-http-server-01#1]
comment

**Comment by sakura818** [comment]
* [x] チェックリストをつくっていく

**Comment by sakura818** [comment]
書き方のチェックリスト
* [ ]  命名規則に一貫性を持つ
* [ ]  例外処理にはtry-catch-finallyではなくtry-with-resource 構文を使う
* [x]  resourcesをtest/resourcesにも置いたほうがいいかも
* [x]  HttpServer.javaの(request = br.readLine()).equals("") はreadLine() が null を返した時に死ぬ
* [x]  コメントはJavaDocに従う(https://www.javadrive.jp/javadoc/comment/index1.html)
* [x]  クラスやメソッドにjavadocを書く
* [ ]  フィールド・変数の生存期間は短くなるように書く
* [x]  if文の入れ子構造やネストを浅くする
* [x]  いらないフィールド・変数は消す
* [x]  適切な型をつかう
* [ ]  this.をつける
* [x]  命名し直す

**Comment by sakura818** [comment]
やることのチェックリスト
* [ ]  単体テストを書く
* [x]  URISyntaxExceptionの例外処理が継承される問題を質問する
* [x]  リクエストラインのメソッド(GETとHEAD)の処理　
* [ ]  レスポンスのファイルを読み込む処理
* [x]  8080問題解消する
* [x]  レスポンスを出力する
* [x]  不要なファイルを削除する(build,.idea)
* [x]  設計のしなおし
* [ ]  足りない部分を足す
* [x]  各メソッドの詳細をみていく(30こ)

**Comment by vvakame** [comment]
> this.をつける

この辺は人によって流儀が違う気がする(Javaに慣れた人はあまり書かない印象がある)。
メソッドの外部に影響がある要素ではないのでプロジェクト内で統一感があれば 🙆

**Comment by vvakame** [comment]
8080問題ってなんじゃろ？

**Comment by sakura818** [comment]
8080問題は何度かプログラムを繰り返し実行しているうちにポート番号が使えなくなることがある問題です。現在、原因を探している途中です。

以下、詳細です。
最初、80番を使用していたのですが何度かログラムを繰り返し実行しているうちにコネクションできない状態になりました。ターミナルでlsof -i :80 をしたら他のプロセス20個ほどに専有されていたため、8080番ポートに切り替えることにしました。
次に8080番を使っていて何度かは上手く行ったんですが、繰り返しプログラムを実行するうちにコネクションできない状態になりました。
8081番も同じ状況になり現在は8082番を使っています。

**Comment by vvakame** [comment]
同一コンピュータ上の同じポートを複数のプロセス（プログラム）から同時に利用することはできないからですね。
1個前の自分のプログラムを殺さずに起動したのでそうなってると思うので、毎回用が終わったら殺すようにしましょう。
最悪、PC毎再起動すればまた使えるようになります。

**Comment by sakura818** [comment]
新しいチェックリスト


- [ ]

**Comment by sakura818** [comment]
新しいチェックリスト　

* [x] ステータスコードが200のとき、テキストファイルがブラウザにファイルが出力されていないのをなおす(HttpResponseMessageBodyContentのwhile文が原因)
* [x] ↑が解決したらバイナリファイルが読み込めるのか確認する
* [x] バイナリファイル(png,jpeg,gif)がブラウザに表示できていないため修正(HttpResponseMessageBodyContent,HttpResponseが原因→なおせる方針のメソッドはたったのでコードなおし中)
* [x] HttpServerTestが4割しかかけていないのでなおす
* [x] HttpResponseStatusLineContentTestのテストが通るようになおす
* [x] HttpResponseMessageHeaderContentTestのテストが通るようになおす
* [x] HttpResponseMessageBodyContentのファイルの読み込みがおそすぎるので少し改善
* [x] HttpResponseMessageBodyContentTestはまだなにも書いていないので書く
* [x] HttpResponseTest以外のすべてのクラスが通るようにする(HttpResponseTestは何も書いていない)
* [x] きちんとしたテストコードの書き方について軽く一通り学ぶ
* [x] ↑がおわったあとにHttpResponseTestは書いたほうがいいのか、書くとしたらどうやって書くのかを学ぶ
* [x] Reformat Code & コードを整理する(いらないフィールドは削除する、無駄な部分を省くなど)
* [x] pull requestを送ってmaster branchにmergeする
* [x] コードレビュー
----------------------------------------------------------------------------------------------------
* [x] クラス名が名詞かつその命名が適切かどうか確認する
* [x] テストクラス名 = テスト対象名 ＋ Test にする
* [x] テストメソッド名は日本語にする
* [x] フィールド名が名詞かつその命名が適切かどうか確認する
* [x] メソッド名が動詞かつその命名が適切かどうか確認する
* [x] クラスの責務が大きくなりすぎていないか確認する→selectStatusCodeメソッドの位置が微妙かもしれない
* [x] メソッドの責務が大きくなりすぎていないか確認する→createHttpResponseMessageBodyメソッドの役割が大きすぎるので分割したほうがいいかもしれない
* [x] printHttpRequestLine()
* [x] InputStreamをフィールドとして保持する意味
* [x] 変数名に関してhttpRequestとrequestの2種類使っているところがあるのでhttpRequestに統一する
* [x] 変数名に関してhttpResponseとresponseの2種類使っているところがあるのでhttpResponseに統一する
* [x] アクセス修飾子が適切かどうか確認する(privateでいいのにpublicにしてたりするのをなおす)
* [x] Reformat Code 
* [x] pull requestを送ってmaster branchにmergeする
* [x] コードレビュー
----------------------------------------------------------------------------------------------------
* [x] ステータスコード400のときを考える
* [x] printRequestLine が、与えられた文字列をprintlnに渡すだけになってて、これはメソッドに分ける意味ない気がする
* [x]  file と filePath を区別
* [x] splitRequestLine メソッドの名前と責務が一致してない
* [x] クラスフィールドのfileは初期化されていないまま、HttpResponseMessageHeaderBuilderのコンストラクタに渡されている
* [x] statusCodeは初期化されていないままコンストラクタ引数
* [x] HttpResponseMessageBodyBuilderのテスト
* [x] HttpRequestTestを書く
* [x] HttpResponseTestを書く
* [x] HttpServerTestを書く
* [x] [Java SE8](https://docs.oracle.com/javase/jp/8)のクラスのメソッドを確認して、自分のコードにおいて処理していない例外処理がないか確認する。処理していなかった場合はコードに追加する
* [x] [Java SE8](https://docs.oracle.com/javase/jp/8)のクラスのメソッドを確認して、自分のコードにおいてcloseされるべきものがされているか確認する(例えばsocket.closeなど)。されていなかった場合はコードに追加する
* [ ] 他の人のコードレビュー・ホワイトボックステストをみてなおせるところをなおしていく
* [x] 変数の生存期間は短くなるように書く
* [x] テストコードでリストをテストするときに書くときに効率よく記述する
* [ ] HashMapにgetOrDefaultを設定する
* [ ] try-catch文をtry-with-resources文になおす
* [ ] HttpResponseMessageBodyContentクラスのバイトの配列なおしたほうがいい(今のままだと2.1GBとかのデータがきたらエラーをおこしそう)
 * [ ] ByteArrayOutputStream
* [ ] fileの読み込みはJavaSE8からFilesクラスでより簡潔にかけるようになったのでなおす
